# Generated by Django 2.1.7 on 2019-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardtier',
            name='remaining_rewards',
        ),
        migrations.AlterField(
            model_name='rewardtier',
            name='total_rewards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
