# Generated by Django 2.1.7 on 2019-03-19 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0003_auto_20190318_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_goal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
