# Generated by Django 2.1.7 on 2019-03-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunder', '0004_auto_20190319_1441'),
        ('crowdfunder', '0004_auto_20190319_1414'),
    ]

    operations = [
    ]
